const fs = require("fs"); const path = require("path");
const structure = {
  "backend/package.json": "{\n  \"name\": \"cineverse-backend\",\n  \"version\": \"1.0.0\",\n  \"main\": \"src/server.js\",\n  \"scripts\": {\n    \"start\": \"node src/server.js\",\n    \"dev\": \"nodemon src/server.js\"\n  },\n  \"dependencies\": {\n    \"axios\": \"^1.7.9\",\n    \"cors\": \"^2.8.5\",\n    \"dotenv\": \"^16.4.7\",\n    \"express\": \"^4.21.2\",\n    \"express-rate-limit\": \"^7.5.0\",\n    \"mongoose\": \"^8.9.5\"\n  },\n  \"devDependencies\": {\n    \"nodemon\": \"^3.1.9\"\n  }\n}",
  "backend/.env.example": "PORT=5000\nTMDB_ACCESS_TOKEN=your_tmdb_bearer_token_here\nMONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/cineverse?retryWrites=true&w=majority\nCLIENT_URL=http://localhost:5173",
  "backend/src/config/db.js": "const mongoose = require(\x27mongoose\x27);\n\nconst connectDB = async () => {\n  try {\n    const conn = await mongoose.connect(process.env.MONGODB_URI);\n    console.log(`MongoDB Connected: ${conn.connection.host}`);\n  } catch (error) {\n    console.error(`Error connecting to MongoDB: ${error.message}`);\n    process.exit(1);\n  }\n};\n\nmodule.exports = connectDB;",
  "backend/src/utils/cache.js": "class Cache {\n  constructor(defaultTTL = 300 * 1000) {\n    this.cache = new Map();\n    this.defaultTTL = defaultTTL;\n  }\n  set(key, value, ttl = this.defaultTTL) {\n    const expiry = Date.now() + ttl;\n    this.cache.set(key, { value, expiry });\n  }\n  get(key) {\n    const item = this.cache.get(key);\n    if (!item) return null;\n    if (Date.now() > item.expiry) {\n      this.cache.delete(key);\n      return null;\n    }\n    return item.value;\n  }\n}\nmodule.exports = new Cache();",
  "backend/src/services/movieService.js": "const axios = require(\x27axios\x27);\nconst cache = require(\x27../utils/cache\x27);\nconst TMDB_BASE_URL = \x27https://api.themoviedb.org/3\x27;\nconst IMAGE_BASE_URL = \x27https://image.tmdb.org/t/p/w500\x27;\nconst BACKDROP_BASE_URL = \x27https://image.tmdb.org/t/p/original\x27;\nconst GENRE_MAP = { 28: \x27Action\x27, 12: \x27Adventure\x27, 16: \x27Animation\x27, 35: \x27Comedy\x27, 80: \x27Crime\x27, 18: \x27Drama\x27, 878: \x27Sci-Fi\x27, 53: \x27Thriller\x27 };\nclass MovieService {\n  constructor() {\n    this.client = axios.create({\n      baseURL: TMDB_BASE_URL,\n      headers: { accept: \x27application/json\x27, Authorization: `Bearer ${process.env.TMDB_ACCESS_TOKEN}` },\n      timeout: 10000\n    });\n  }\n  normalizeMovie(item) {\n    const primaryGenreId = item.genre_ids?.[0];\n    return {\n      id: item.id,\n      title: item.title || \x27Untitled\x27,\n      overview: item.overview || \x27No overview available.\x27,\n      poster: item.poster_path ? `${IMAGE_BASE_URL}${item.poster_path}` : \x27https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500\x27,\n      backdrop: item.backdrop_path ? `${BACKDROP_BASE_URL}${item.backdrop_path}` : null,\n      releaseDate: item.release_date || \x27Unknown\x27,\n      releaseYear: (item.release_date || \x27\x27).substring(0, 4) || \x27N/A\x27,\n      rating: item.vote_average ? Number(item.vote_average.toFixed(1)) : null,\n      genre: primaryGenreId ? (GENRE_MAP[primaryGenreId] || \x27General\x27) : \x27General\x27\n    };\n  }\n  async getMovies({ query, genre, sort = \x27popularity\x27, page = 1 }) {\n    const cacheKey = `movies:${query}:${genre}:${sort}:${page}`;\n    const cached = cache.get(cacheKey);\n    if (cached) return cached;\n    let endpoint = \x27/movie/popular\x27;\n    let params = { page: Number(page) };\n    if (query && query.trim()) {\n      endpoint = \x27/search/movie\x27;\n      params.query = query.trim();\n    }\n    const res = await this.client.get(endpoint, { params });\n    const results = res.data.results.map(item => this.normalizeMovie(item));\n    const payload = { movies: results, page: res.data.page, totalPages: Math.min(res.data.total_pages, 500), hasMore: res.data.page < res.data.total_pages };\n    cache.set(cacheKey, payload);\n    return payload;\n  }\n  async getMovieDetails(id) {\n    const res = await this.client.get(`/movie/${id}`);\n    return this.normalizeMovie(res.data);\n  }\n}\nmodule.exports = new MovieService();",
  "backend/src/models/WishlistItem.js": "const mongoose = require(\x27mongoose\x27);\nconst WishlistItemSchema = new mongoose.Schema({\n  userId: { type: String, required: true, index: true },\n  movieId: { type: Number, required: true },\n  title: { type: String, required: true },\n  poster: { type: String },\n  releaseYear: { type: String },\n  rating: { type: Number },\n  genre: { type: String },\n  createdAt: { type: Date, default: Date.now }\n});\nWishlistItemSchema.index({ userId: 1, movieId: 1 }, { unique: true });\nmodule.exports = mongoose.model(\x27WishlistItem\x27, WishlistItemSchema);",
  "backend/src/services/wishlistService.js": "const WishlistItem = require(\x27../models/WishlistItem\x27);\nclass WishlistService {\n  async getWishlist(userId) { return await WishlistItem.find({ userId }).sort({ createdAt: -1 }); }\n  async addWishlistItem(userId, data) {\n    return await WishlistItem.findOneAndUpdate({ userId, movieId: data.movieId }, { userId, ...data }, { upsert: true, new: true });\n  }\n  async removeWishlistItem(userId, movieId) { return await WishlistItem.findOneAndDelete({ userId, movieId }); }\n}\nmodule.exports = new WishlistService();",
  "backend/src/controllers/movieController.js": "const s = require(\x27../services/movieService\x27);\nmodule.exports = {\n  async getMovies(req, res, next) { try { res.json(await s.getMovies(req.query)); } catch (e) { next(e); } },\n  async getMovieDetails(req, res, next) { try { res.json(await s.getMovieDetails(req.params.id)); } catch (e) { next(e); } }\n};",
  "backend/src/controllers/wishlistController.js": "const s = require(\x27../services/wishlistService\x27);\nmodule.exports = {\n  async getWishlist(req, res, next) { try { res.json(await s.getWishlist(req.headers[\x27x-user-id\x27] || \x27default\x27)); } catch (e) { next(e); } },\n  async addToWishlist(req, res, next) { try { res.status(201).json(await s.addWishlistItem(req.headers[\x27x-user-id\x27] || \x27default\x27, req.body)); } catch (e) { next(e); } },\n  async removeFromWishlist(req, res, next) { try { await s.removeWishlistItem(req.headers[\x27x-user-id\x27] || \x27default\x27, Number(req.params.movieId)); res.json({ success: true }); } catch (e) { next(e); } }\n};",
  "backend/src/middleware/errorHandler.js": "module.exports = (err, req, res, next) => { console.error(err); res.status(500).json({ error: err.message }); };",
  "backend/src/middleware/rateLimiter.js": "const rateLimit = require(\x27express-rate-limit\x27);\nmodule.exports = rateLimit({ windowMs: 15*60*1000, max: 200 });",
  "backend/src/routes/movieRoutes.js": "const r = require(\x27express\x27).Router(); const c = require(\x27../controllers/movieController\x27);\nr.get(\x27/\x27, c.getMovies); r.get(\x27/:id\x27, c.getMovieDetails);\nmodule.exports = r;",
  "backend/src/routes/wishlistRoutes.js": "const r = require(\x27express\x27).Router(); const c = require(\x27../controllers/wishlistController\x27);\nr.get(\x27/\x27, c.getWishlist); r.post(\x27/\x27, c.addToWishlist);\nr.delete(\x27/:movieId\x27, c.removeFromWishlist);\nmodule.exports = r;",
  "backend/src/server.js": "const express = require(\x27express\x27); const cors = require(\x27cors\x27); const dotenv = require(\x27dotenv\x27); const connectDB = require(\x27./config/db\x27);\ndotenv.config(); if (process.env.MONGODB_URI) connectDB();\nconst app = express(); app.use(cors()); app.use(express.json());\napp.use(\x27/api/\x27, require(\x27./middleware/rateLimiter\x27));\napp.use(\x27/api/movies\x27, require(\x27./routes/movieRoutes\x27));\napp.use(\x27/api/wishlist\x27, require(\x27./routes/wishlistRoutes\x27));\napp.use(require(\x27./middleware/errorHandler\x27));\napp.listen(5000, () => console.log(\x27Backend running on 5000\x27));",
  "frontend/package.json": "{\n  \"name\": \"cineverse-frontend\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": { \"dev\": \"vite\" },\n  \"dependencies\": { \"axios\": \"^1.7.9\", \"lucide-react\": \"^1.16.0\", \"react\": \"^18.3.1\", \"react-dom\": \"^18.3.1\" },\n  \"devDependencies\": { \"@vitejs/plugin-react\": \"^4.3.1\", \"autoprefixer\": \"^10.4.20\", \"postcss\": \"^8.4.47\", \"tailwindcss\": \"^3.4.13\", \"vite\": \"^5.4.2\" }\n}",
  "frontend/.env.example": "VITE_API_BASE_URL=http://localhost:5000/api",
  "frontend/index.html": "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>CineVerse</title></head><body class=\"bg-slate-950 text-slate-100\"><div id=\"root\"></div><script type=\"module\" src=\"/src/main.jsx\"></script></body></html>",
  "frontend/src/main.jsx": "import React from \x27react\x27; import ReactDOM from \x27react-dom/client\x27; import App from \x27./App.jsx\x27; import \x27./index.css\x27;\nReactDOM.createRoot(document.getElementById(\x27root\x27)).render(<React.StrictMode><App /></React.StrictMode>);",
  "frontend/src/index.css": "@tailwind base; @tailwind components; @tailwind utilities;",
  "frontend/src/api/movieApi.js": "import axios from \x27axios\x27;\nconst BASE = \x27http://localhost:5000/api\x27;\nexport const movieApi = {\n  async getMovies(p) { return (await axios.get(`${BASE}/movies`, { params: p })).data; },\n  async getMovieDetails(id) { return (await axios.get(`${BASE}/movies/${id}`)).data; }\n};",
  "frontend/src/api/wishlistApi.js": "import axios from \x27axios\x27;\nconst BASE = \x27http://localhost:5000/api\x27;\nconst getUid = () => { let u = localStorage.getItem(\x27cineverse_uid\x27); if (!u) { u = \x27u_\x27 + Math.random().toString(36).slice(2); localStorage.setItem(\x27cineverse_uid\x27, u); } return u; };\nexport const wishlistApi = {\n  async getWishlist() { return (await axios.get(`${BASE}/wishlist`, { headers: { \x27x-user-id\x27: getUid() } })).data; },\n  async addToWishlist(m) { return (await axios.post(`${BASE}/wishlist`, m, { headers: { \x27x-user-id\x27: getUid() } })).data; },\n  async removeFromWishlist(id) { return (await axios.delete(`${BASE}/wishlist/${id}`, { headers: { \x27x-user-id\x27: getUid() } })).data; }\n};",
  "frontend/src/App.jsx": "import React, { useState, useEffect } from \x27react\x27;\nimport { movieApi } from \x27./api/movieApi\x27;\nimport { wishlistApi } from \x27./api/wishlistApi\x27;\nimport { Search, Heart, Star } from \x27lucide-react\x27;\nexport default function App() {\n  const [movies, setMovies] = useState([]);\n  const [wishlist, setWishlist] = useState([]);\n  const [query, setQuery] = useState(\x27\x27);\n  useEffect(() => { wishlistApi.getWishlist().then(setWishlist).catch(() => {}); }, []);\n  useEffect(() => { movieApi.getMovies({ query }).then(d => setMovies(d.movies)).catch(() => {}); }, [query]);\n  const toggle = async (m) => {\n    const id = m.id || m.movieId;\n    if (wishlist.some(i => i.movieId === id)) {\n      await wishlistApi.removeFromWishlist(id);\n      setWishlist(prev => prev.filter(i => i.movieId !== id));\n    } else {\n      const saved = await wishlistApi.addToWishlist({ movieId: id, title: m.title, poster: m.poster, releaseYear: m.releaseYear, rating: m.rating, genre: m.genre });\n      setWishlist(prev => [saved, ...prev]);\n    }\n  };\n  return (\n    <div className=\"min-h-screen bg-slate-950 text-white p-8\">\n      <h1 className=\"text-3xl font-black text-red-600 mb-6\">CINEVERSE</h1>\n      <div className=\"mb-6\"><input type=\"text\" placeholder=\"Search movies...\" value={query} onChange={e => setQuery(e.target.value)} className=\"bg-slate-900 border border-slate-800 p-3 rounded-xl w-full max-w-md\" /></div>\n      <div className=\"grid grid-cols-2 md:grid-cols-4 gap-6\">\n        {movies.map(m => (\n          <div key={m.id} className=\"bg-slate-900 border border-slate-800 rounded-xl overflow-hidden p-3 relative\">\n            <img src={m.poster} alt={m.title} className=\"w-full h-72 object-cover rounded-lg mb-2\" />\n            <h3 className=\"font-bold truncate\">{m.title}</h3>\n            <button onClick={() => toggle(m)} className=\"absolute top-5 right-5 bg-black/60 p-2 rounded-full\"><Heart className={`w-5 h-5 ${wishlist.some(i => i.movieId === m.id) ? \x27text-red-500 fill-red-500\x27 : \x27text-white\x27}`} /></button>\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n}\n"
};
Object.entries(structure).forEach(([p, c]) => {
  const full = path.join(process.cwd(), p);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, c, "utf-8");
  console.log("Created: " + p);
});
console.log("Done!");
